name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [master, develop]

jobs:
  PHPUnit:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: unittest
      adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: 7.3
    - uses: actions/checkout@v2

    - name: Copy the .env
      run: cp .env.example .env
    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Configrue Storage Permission
      run: chmod -R 777 storage bootstrap/cache
    - name: Generate Application Key
      run: php artisan key:generate
    - name: Clear Configuration
      run: php artisan config:clear
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_PORT: 8080
        DB_USER: root
        DB_PASSWORD: example
        DB_DATABASE: unittest
      run: vendor/bin/phpunit